language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - find ./Grid ./DependencyInjection ./Twig -name "*.php" -exec php -l {} \;
  - ./bin/phpcs --extensions=php --standard=PSR2 ./Grid ./DependencyInjection ./Twig